/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CategorySchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'icon', 'id', 'image', 'metaDescription', 'metaTitle', 'name', 'parentId', 'slug', 'sortOrder', 'updatedAt'] as const
  $columns = CategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare icon: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare image: string | null
  @column()
  declare metaDescription: string | null
  @column()
  declare metaTitle: string | null
  @column()
  declare name: string
  @column()
  declare parentId: number | null
  @column()
  declare slug: string
  @column()
  declare sortOrder: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CommentSchema extends BaseModel {
  static $columns = ['approvedAt', 'authorEmail', 'authorName', 'authorWebsite', 'content', 'createdAt', 'deletedAt', 'id', 'ipAddress', 'parentId', 'postId', 'status', 'updatedAt', 'userAgent'] as const
  $columns = CommentSchema.$columns
  @column.dateTime()
  declare approvedAt: DateTime | null
  @column()
  declare authorEmail: string
  @column()
  declare authorName: string
  @column()
  declare authorWebsite: string | null
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ipAddress: string | null
  @column()
  declare parentId: number | null
  @column()
  declare postId: number
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userAgent: string | null
}

export class ContactRequestSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id', 'message', 'name', 'phone', 'status', 'subject', 'updatedAt'] as const
  $columns = ContactRequestSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare message: string
  @column()
  declare name: string
  @column()
  declare phone: string | null
  @column()
  declare status: string | null
  @column()
  declare subject: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MenuItemSchema extends BaseModel {
  static $columns = ['createdAt', 'cssClass', 'id', 'menuId', 'parentId', 'referenceId', 'rel', 'sortOrder', 'target', 'title', 'type', 'updatedAt', 'url'] as const
  $columns = MenuItemSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare cssClass: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare menuId: number
  @column()
  declare parentId: number | null
  @column()
  declare referenceId: number | null
  @column()
  declare rel: string | null
  @column()
  declare sortOrder: number
  @column()
  declare target: string
  @column()
  declare title: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare url: string | null
}

export class MenuSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'description', 'id', 'isDefault', 'location', 'name', 'slug', 'updatedAt'] as const
  $columns = MenuSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isDefault: boolean
  @column()
  declare location: string | null
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class NewsletterSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id', 'isActive', 'updatedAt'] as const
  $columns = NewsletterSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PageSchema extends BaseModel {
  static $columns = ['canonicalUrl', 'content', 'coverImage', 'createdAt', 'deletedAt', 'excerpt', 'focusKeyword', 'id', 'isHomepage', 'metaDescription', 'metaTitle', 'publishedAt', 'slug', 'status', 'template', 'title', 'updatedAt'] as const
  $columns = PageSchema.$columns
  @column()
  declare canonicalUrl: string | null
  @column()
  declare content: string
  @column()
  declare coverImage: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare excerpt: string | null
  @column()
  declare focusKeyword: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isHomepage: boolean
  @column()
  declare metaDescription: string | null
  @column()
  declare metaTitle: string | null
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column()
  declare slug: string
  @column()
  declare status: string
  @column()
  declare template: string | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PermissionRoleSchema extends BaseModel {
  static $columns = ['deletedAt', 'permissionId', 'roleId'] as const
  $columns = PermissionRoleSchema.$columns
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare permissionId: number | null
  @column()
  declare roleId: number | null
}

export class PermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'description', 'id', 'module', 'name', 'slug', 'updatedAt'] as const
  $columns = PermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare module: string
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PostTagSchema extends BaseModel {
  static $columns = ['postId', 'tagId'] as const
  $columns = PostTagSchema.$columns
  @column()
  declare postId: number | null
  @column()
  declare tagId: number | null
}

export class PostSchema extends BaseModel {
  static $columns = ['canonicalUrl', 'categoryId', 'content', 'coverImage', 'createdAt', 'deletedAt', 'excerpt', 'focusKeyword', 'id', 'metaDescription', 'metaTitle', 'publishedAt', 'seriesId', 'slug', 'status', 'title', 'updatedAt', 'views', 'wordpressId'] as const
  $columns = PostSchema.$columns
  @column()
  declare canonicalUrl: string | null
  @column()
  declare categoryId: number | null
  @column()
  declare content: string
  @column()
  declare coverImage: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare excerpt: string | null
  @column()
  declare focusKeyword: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare metaDescription: string | null
  @column()
  declare metaTitle: string | null
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column()
  declare seriesId: number | null
  @column()
  declare slug: string
  @column()
  declare status: string | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare views: number
  @column()
  declare wordpressId: number | null
}

export class ProjectSchema extends BaseModel {
  static $columns = ['content', 'createdAt', 'demoUrl', 'description', 'featured', 'id', 'repoUrl', 'slug', 'status', 'techStack', 'thumbnailUrl', 'title', 'updatedAt'] as const
  $columns = ProjectSchema.$columns
  @column()
  declare content: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare demoUrl: string | null
  @column()
  declare description: string | null
  @column()
  declare featured: boolean | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare repoUrl: string | null
  @column()
  declare slug: string
  @column()
  declare status: string
  @column()
  declare techStack: any | null
  @column()
  declare thumbnailUrl: string | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class QuestionAnswerSchema extends BaseModel {
  static $columns = ['answer', 'createdAt', 'id', 'isPublished', 'postId', 'question', 'sortOrder', 'updatedAt'] as const
  $columns = QuestionAnswerSchema.$columns
  @column()
  declare answer: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isPublished: boolean | null
  @column()
  declare postId: number
  @column()
  declare question: string
  @column()
  declare sortOrder: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RoleUserSchema extends BaseModel {
  static $columns = ['deletedAt', 'id', 'roleId', 'userId'] as const
  $columns = RoleUserSchema.$columns
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare roleId: number | null
  @column()
  declare userId: number | null
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'description', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SeriesSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = SeriesSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SettingSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'label', 'settingGroup', 'settingKey', 'settingValue', 'sortOrder', 'type', 'updatedAt'] as const
  $columns = SettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare label: string
  @column()
  declare settingGroup: string
  @column()
  declare settingKey: string
  @column()
  declare settingValue: any | null
  @column()
  declare sortOrder: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TagSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'metaDescription', 'metaTitle', 'name', 'slug', 'updatedAt'] as const
  $columns = TagSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare metaDescription: string | null
  @column()
  declare metaTitle: string | null
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ToolSchema extends BaseModel {
  static $columns = ['category', 'createdAt', 'deletedAt', 'description', 'featured', 'icon', 'id', 'name', 'slug', 'sortOrder', 'status', 'updatedAt', 'urlPath'] as const
  $columns = ToolSchema.$columns
  @column()
  declare category: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare featured: boolean | null
  @column()
  declare icon: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare sortOrder: number | null
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare urlPath: string
}

export class UserSchema extends BaseModel {
  static $columns = ['activeEmail', 'createdAt', 'deletedAt', 'email', 'fullName', 'id', 'password', 'status', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare activeEmail: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
