/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CategorySchema extends BaseModel {
  static $columns = ['color', 'createdAt', 'description', 'icon', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = CategorySchema.$columns
  @column()
  declare color: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare icon: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ContactRequestSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id', 'message', 'name', 'status', 'subject', 'updatedAt'] as const
  $columns = ContactRequestSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare message: string
  @column()
  declare name: string
  @column()
  declare status: string | null
  @column()
  declare subject: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class NewsletterSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id', 'updatedAt'] as const
  $columns = NewsletterSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PermissionRoleSchema extends BaseModel {
  static $columns = ['deletedAt', 'permissionId', 'roleId'] as const
  $columns = PermissionRoleSchema.$columns
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare permissionId: string
  @column()
  declare roleId: number
}

export class PermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'module', 'name', 'slug', 'updatedAt'] as const
  $columns = PermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare module: string
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PostTagSchema extends BaseModel {
  static $columns = ['postId', 'tagId'] as const
  $columns = PostTagSchema.$columns
  @column()
  declare postId: string | null
  @column()
  declare tagId: string | null
}

export class PostSchema extends BaseModel {
  static $columns = ['categoryId', 'content', 'coverImage', 'createdAt', 'excerpt', 'id', 'seriesId', 'slug', 'status', 'title', 'updatedAt'] as const
  $columns = PostSchema.$columns
  @column()
  declare categoryId: string | null
  @column()
  declare content: string
  @column()
  declare coverImage: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare excerpt: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare seriesId: string | null
  @column()
  declare slug: string
  @column()
  declare status: string | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProjectSchema extends BaseModel {
  static $columns = ['createdAt', 'demoUrl', 'description', 'featured', 'id', 'repoUrl', 'slug', 'techStack', 'thumbnailUrl', 'title', 'updatedAt'] as const
  $columns = ProjectSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare demoUrl: string | null
  @column()
  declare description: string | null
  @column()
  declare featured: boolean | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare repoUrl: string | null
  @column()
  declare slug: string
  @column()
  declare techStack: any | null
  @column()
  declare thumbnailUrl: string | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RoleUserSchema extends BaseModel {
  static $columns = ['deletedAt', 'id', 'roleId', 'userId'] as const
  $columns = RoleUserSchema.$columns
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare roleId: number | null
  @column()
  declare userId: number | null
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'description', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SeriesSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = SeriesSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ServiceSchema extends BaseModel {
  static $columns = ['category', 'createdAt', 'description', 'featured', 'features', 'id', 'name', 'priceRange', 'slug', 'updatedAt'] as const
  $columns = ServiceSchema.$columns
  @column()
  declare category: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare featured: boolean | null
  @column()
  declare features: any | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare priceRange: string | null
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TagSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = TagSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['activeEmail', 'createdAt', 'deletedAt', 'email', 'fullName', 'id', 'password', 'status', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare activeEmail: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
