/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Categories: () => import('#controllers/categories_controller'),
  Contacts: () => import('#controllers/contacts_controller'),
  Media: () => import('#controllers/media_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Permissions: () => import('#controllers/permissions_controller'),
  Posts: () => import('#controllers/posts_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Projects: () => import('#controllers/projects_controller'),
  Roles: () => import('#controllers/roles_controller'),
  Services: () => import('#controllers/services_controller'),
  Settings: () => import('#controllers/settings_controller'),
  Tags: () => import('#controllers/tags_controller'),
  Users: () => import('#controllers/users_controller'),
}
