import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Tool from '#models/tool'

export default class extends BaseSeeder {
  async run() {
    const tools = [
      {
        slug: 'uuid-generator',
        name: 'UUID Generator',
        description: 'Generate random UUID v4 identifiers',
        category: 'Generator',
        urlPath: '/tools/uuid-generator',
        featured: true,
        status: 'PUBLISHED' as const,
        sortOrder: 1,
      },
      {
        slug: 'token-generator',
        name: 'Token Generator',
        description: 'Generate random tokens with custom length',
        category: 'Generator',
        urlPath: '/tools/token-generator',
        featured: true,
        status: 'PUBLISHED' as const,
        sortOrder: 2,
      },
      {
        slug: 'password-generator',
        name: 'Password Generator',
        description: 'Generate secure passwords with custom options',
        category: 'Generator',
        urlPath: '/tools/password-generator',
        featured: true,
        status: 'PUBLISHED' as const,
        sortOrder: 3,
      },
      {
        slug: 'slug-generator',
        name: 'Slug Generator',
        description: 'Convert text to URL-friendly slugs',
        category: 'Generator',
        urlPath: '/tools/slug-generator',
        featured: false,
        status: 'PUBLISHED' as const,
        sortOrder: 4,
      },
      {
        slug: 'lorem-ipsum-generator',
        name: 'Lorem Ipsum Generator',
        description: 'Generate placeholder text for designs',
        category: 'Generator',
        urlPath: '/tools/lorem-ipsum-generator',
        featured: false,
        status: 'PUBLISHED' as const,
        sortOrder: 5,
      },
      {
        slug: 'base64-encoder-decoder',
        name: 'Base64 Encoder/Decoder',
        description: 'Encode and decode Base64 strings',
        category: 'Encoder',
        urlPath: '/tools/base64-encoder-decoder',
        featured: true,
        status: 'PUBLISHED' as const,
        sortOrder: 6,
      },
      {
        slug: 'url-encoder-decoder',
        name: 'URL Encoder/Decoder',
        description: 'Encode and decode URL strings',
        category: 'Encoder',
        urlPath: '/tools/url-encoder-decoder',
        featured: false,
        status: 'PUBLISHED' as const,
        sortOrder: 7,
      },
      {
        slug: 'html-entities',
        name: 'HTML Entities Encoder/Decoder',
        description: 'Encode and decode HTML entities',
        category: 'Encoder',
        urlPath: '/tools/html-entities',
        featured: false,
        status: 'PUBLISHED' as const,
        sortOrder: 8,
      },
      {
        slug: 'hash-generator',
        name: 'Hash Generator',
        description: 'Generate SHA-1, SHA-256, SHA-384, SHA-512 hashes',
        category: 'Encoder',
        urlPath: '/tools/hash-generator',
        featured: true,
        status: 'PUBLISHED' as const,
        sortOrder: 9,
      },
      {
        slug: 'jwt-decoder',
        name: 'JWT Decoder',
        description: 'Decode JWT tokens to view header and payload',
        category: 'Encoder',
        urlPath: '/tools/jwt-decoder',
        featured: false,
        status: 'PUBLISHED' as const,
        sortOrder: 10,
      },
      {
        slug: 'case-converter',
        name: 'Case Converter',
        description: 'Convert text between camelCase, snake_case, kebab-case, etc.',
        category: 'Converter',
        urlPath: '/tools/case-converter',
        featured: false,
        status: 'PUBLISHED' as const,
        sortOrder: 11,
      },
      {
        slug: 'timestamp-converter',
        name: 'Unix Timestamp Converter',
        description: 'Convert between Unix timestamps and datetime',
        category: 'Converter',
        urlPath: '/tools/timestamp-converter',
        featured: false,
        status: 'PUBLISHED' as const,
        sortOrder: 12,
      },
      {
        slug: 'color-converter',
        name: 'Color Converter',
        description: 'Convert between HEX, RGB, and HSL color formats',
        category: 'Converter',
        urlPath: '/tools/color-converter',
        featured: false,
        status: 'PUBLISHED' as const,
        sortOrder: 13,
      },
      {
        slug: 'json-formatter',
        name: 'JSON Formatter',
        description: 'Format and validate JSON data',
        category: 'Text',
        urlPath: '/tools/json-formatter',
        featured: true,
        status: 'PUBLISHED' as const,
        sortOrder: 14,
      },
      {
        slug: 'cron-builder',
        name: 'Cron Expression Builder',
        description: 'Build and understand cron expressions',
        category: 'Developer',
        urlPath: '/tools/cron-builder',
        featured: false,
        status: 'PUBLISHED' as const,
        sortOrder: 15,
      },
    ]

    for (const tool of tools) {
      await Tool.updateOrCreate({ slug: tool.slug }, tool)
    }
  }
}
